Study\Credential\Domain\Model\Infrastructure\Doctrine\DoctrineCredential:
  type: entity
  table: credential
  id:
    id:
      type: string
      length: 255
  fields:
    label:
      type: string
      length: 255
    key:
      type: string
      length: 255
      column: _key
      unique: true
