Study\User\Domain\Model\Infrastructure\Doctrine\DoctrineUser:
  type: entity
  table: user
  id:
    id:
      type: string
      length: 255
  fields:
    email:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255
