services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Study\Credential\Domain\Repository\CredentialRepository:
    alias: Study\Credential\Domain\Repository\Infrastructure\Doctrine\DoctrineCredentialRepository


  Study\Credential\Domain\Repository\Infrastructure\Doctrine\DoctrineCredentialRepository:
    lazy: true
